### MAD LIBS ###
### https://i.pinimg.com/736x/4f/d2/fd/4fd2fdcd1a24611d0bbd238876096bbe--outer-space-camp-mad-libs-for-adults.jpg ###
print("Give me an adjective.")
adj1 = input()
print("A noun?")
noun1 = input()
print("Adjective?")
adj2 = input()
print("Give me a plural noun.")
pluralnoun1 = input()
print("Can I have an adverb?")
adverb1 = input()
print("Give me a verb ending in ing")
verbendingining1 = input()
print("Can I have a plural silly word?")
sillyword1 = input()
print("Give me an adjective.")
adj3 = input()
print("Can I have a plural noun?")
pluralnoun2 = input()
print("Can I have your first name?")
firstname1 = input()
print("Give me another adjective.")
adj4 = input()
print("Can I have a number?")
number = input()
print("Give me first name.")
firstname2 = input()
print("Can I have another first name?")
firstname3 = input()
print("Another first name?")
firstname4 = input()
print("One more first name?")
firstname5 = input()
print("Can I have a plural noun.")
pluralnoun3 = input()


print("When we look up into the sky on a/an " + adj1 + " summer night, we see millions of tiny spots of light.")
print("Each one represents a/an " + noun1 + " which is the center of a/an " + adj2 + " solar system with dozens of " + pluralnoun1 + " revolving " + adverb1 + " around a distant sun.")
print("Sometimes these suns expand and begin " + verbendingining1 + " their neighbors.")
print("Soon they will become so big, they will turn into " + sillyword1 + ".")
print("Eventually they subside and become " + adj3 + " giants or perhaps black " + pluralnoun2 + ".")   
print("Our own planet, which we call " + firstname1 + " circles around our " + adj4 + " sun " + number + " times a year.")
print("There are eight other planets in our solar system.")
print("They are named " + firstname2 + ", " + firstname3 + ", " + firstname4 + ", " + firstname5 +  " Jupiter, and Mars.")
print("Scientists who study these planets are called " + pluralnoun3 + ".")
